version: "3.3"
services:
  oracle:
    image: "switchboardlabs/node:${SBV2_ORACLE_VERSION:-dev-v2-07-11-22}" # https://hub.docker.com/r/switchboardlabs/node/tags
    network_mode: host
    restart: always
    secrets:
      - PAYER_SECRETS
    environment:
      - VERBOSE=1
      - LIVE=1
      - CLUSTER=${CLUSTER:-localnet}
      - HEARTBEAT_INTERVAL=30 # Seconds
      - ORACLE_KEY=5shyzhuvdw2SF2g4mGUKRaStvrXT5k6TK2v13FMGLrLa
    #  - RPC_URL=${RPC_URL}
secrets:
  PAYER_SECRETS:
    file: ../sdk/tests/test_wallet.json
